import { useState } from 'react';
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { Alert, Box, Button, Card, Chip, Dialog, DialogActions, DialogContent, DialogTitle, MenuItem, Stack, TextField, Typography } from '@mui/material';
import { AddRounded, MenuBookOutlined } from '@mui/icons-material';
import { api, ApiError } from '../../api/client';
import type { AccountingJournal } from '../../types/api';
import { journalTypeLabels } from './options';

export function JournalsPanel({ organizationId, dossierId, journals, archived, canManage }: { organizationId: string; dossierId: string; journals: AccountingJournal[]; archived: boolean; canManage: boolean }) {
  const queryClient = useQueryClient();
  const [open, setOpen] = useState(false);
  const [code, setCode] = useState('');
  const [name, setName] = useState('');
  const [type, setType] = useState('OPERATIONS_DIVERSES');
  const [error, setError] = useState('');
  const mutation = useMutation({ mutationFn: () => api.post<AccountingJournal>(`/api/organizations/${organizationId}/dossiers/${dossierId}/journals`, { code: code.trim(), name: name.trim(), type }), onSuccess: async () => { await queryClient.invalidateQueries({ queryKey: ['journals', organizationId, dossierId] }); setOpen(false); setCode(''); setName(''); setError(''); }, onError: (reason) => setError(reason instanceof ApiError ? reason.message : 'Impossible de créer le journal.') });
  return <><Card><Box sx={{ p: 2.5, display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: 2, flexWrap: 'wrap' }}><Box><Typography variant="h3" sx={{ fontSize: 24 }}>Journaux comptables</Typography><Typography variant="body2" color="text.secondary">Journaux utilisés pour classer et centraliser les écritures.</Typography></Box>{canManage && !archived && <Button variant="contained" startIcon={<AddRounded />} onClick={() => { setError(''); setOpen(true); }}>Nouveau journal</Button>}</Box>{journals.length === 0 && <Box sx={{ p: 6, textAlign: 'center' }}><MenuBookOutlined sx={{ fontSize: 44, color: 'text.disabled' }} /><Typography sx={{ fontWeight: 800, mt: 1 }}>Aucun journal</Typography></Box>}<Box sx={{ display: 'grid', gridTemplateColumns: { xs: '1fr', md: 'repeat(2, 1fr)' } }}>{journals.map((journal) => <Box key={journal.id} sx={{ px: 3, py: 2.2, borderTop: '1px solid', borderRight: { md: '1px solid' }, borderColor: 'divider', display: 'flex', alignItems: 'center', gap: 2 }}><Box sx={{ width: 44, height: 44, borderRadius: 3, bgcolor: 'primary.light', color: 'primary.main', display: 'grid', placeItems: 'center', fontWeight: 900 }}>{journal.code.slice(0, 3)}</Box><Box sx={{ flex: 1 }}><Typography sx={{ fontWeight: 900 }}>{journal.name}</Typography><Typography variant="caption" color="text.secondary">Code {journal.code}</Typography></Box><Chip label={journalTypeLabels[journal.type] ?? journal.type} size="small" variant="outlined" /></Box>)}</Box></Card><Dialog open={open} onClose={mutation.isPending ? undefined : () => setOpen(false)} fullWidth maxWidth="xs"><DialogTitle>Créer un journal</DialogTitle><DialogContent sx={{ display: 'grid', gap: 2, pt: '12px !important' }}>{error && <Alert severity="error">{error}</Alert>}<Stack direction="row" spacing={2}><TextField label="Code" value={code} onChange={(event) => setCode(event.target.value.toUpperCase())} required sx={{ width: 130 }} /><TextField label="Nom" value={name} onChange={(event) => setName(event.target.value)} required fullWidth /></Stack><TextField select label="Type" value={type} onChange={(event) => setType(event.target.value)}>{Object.entries(journalTypeLabels).map(([value, label]) => <MenuItem key={value} value={value}>{label}</MenuItem>)}</TextField></DialogContent><DialogActions><Button onClick={() => setOpen(false)}>Annuler</Button><Button variant="contained" disabled={!code.trim() || !name.trim() || mutation.isPending} onClick={() => mutation.mutate()}>Créer</Button></DialogActions></Dialog></>;
}
